#! /bin/bash
#===============================
#
# yocto-make
#
# 2021/06/10 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname`

${TOP}/script/guide.py
