#! /bin/bash
#===============================
#
# yocto-make
#
# 2021/06/10 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname`

${TOP}/scripts/checkout.sh	$@
[ $? != 0 ] && exit 1

${TOP}/scripts/make.sh		$@
